import os
import glob
import pandas as pd
import ollama
import json
from tqdm import tqdm

BATCH_SIZE = 50
INPUT_DIR = "raw-data"
GENERATED_DIR = "prepared_data"
OLLAMA_MODEL = "gemma4:31b" # Default local judge

def get_judge_prompt(raw_chunk_json, generated_text):
    return f"""
You are an expert Agricultural Data Validator.
Your task is to compare a block of RAW Indian Farmer Q&A logs with a SYNTHESIZED educational article generated by another AI.

RAW DATA (JSON):
{raw_chunk_json}

SYNTHESIZED ARTICLE:
{generated_text}

Analyze the article strictly against the raw data:
1. Hallucinations: Does the article state facts, chemicals, or numbers that do NOT exist in the raw data?
2. Omissions: Did the article miss any critical agricultural diseases, crops, or treatments mentioned in the raw data?

Output ONLY a valid JSON object matching this schema:
{{
    "score": 9,
    "hallucinations": ["list of hallucinated facts", ...],
    "omissions": ["list of missing facts", ...],
    "is_valid": true
}}
Do not output markdown, just the JSON string.
"""

def load_aligned_data(filename):
    """Loads the CSV and the corresponding _cpt.txt file, yielding perfectly aligned chunks."""
    csv_path = os.path.join(INPUT_DIR, filename)
    txt_path = os.path.join(GENERATED_DIR, filename.replace('.csv', '_cpt.txt'))
    
    if not os.path.exists(csv_path) or not os.path.exists(txt_path):
        print(f"Missing files for {filename}")
        return []

    print(f"Loading raw data from {csv_path}...")
    df = pd.read_csv(csv_path, low_memory=False)
    df = df.dropna(subset=['QueryText', 'KccAns'])
    
    print(f"Loading synthesized text from {txt_path}...")
    with open(txt_path, 'r', encoding='utf-8') as f:
        txt_content = f.read()
    
    # Split by the exact EOS delimiter
    blocks = [block.strip() for block in txt_content.split('<eos>') if block.strip()]
    
    aligned_pairs = []
    total_rows = len(df)
    
    for i, start_idx in enumerate(range(0, total_rows, BATCH_SIZE)):
        if i >= len(blocks):
            break # Text file is shorter than CSV
            
        generated_text = blocks[i]
        
        # We successfully ignore skipped chunks while maintaining 1-to-1 alignment!
        if generated_text == "<SKIPPED_CHUNK>":
            continue 
            
        batch_df = df.iloc[start_idx:start_idx+BATCH_SIZE]
        raw_json = json.dumps(batch_df[['QueryText', 'KccAns']].to_dict(orient='records'), ensure_ascii=False)
        
        aligned_pairs.append({
            "chunk_index": i,
            "raw_json": raw_json,
            "generated_text": generated_text
        })
        
    return aligned_pairs

def validate_with_ollama(filename):
    print(f"\n--- Starting local Ollama validation for {filename} ---")
    pairs = load_aligned_data(filename)
    
    for pair in tqdm(pairs, desc="Judging Chunks (Ollama)"):
        prompt = get_judge_prompt(pair['raw_json'], pair['generated_text'])
        
        try:
            response = ollama.chat(
                model=OLLAMA_MODEL,
                messages=[{'role': 'user', 'content': prompt}],
                format="json", # Force JSON output
                keep_alive=-1
            )
            result = response['message']['content'].strip()
            print(f"\n[Chunk {pair['chunk_index']} Verdict]: {result}")
        except Exception as e:
            print(f"Error calling Ollama on chunk {pair['chunk_index']}: {e}")

def prepare_gemini_batch(filename):
    print(f"\n--- Preparing Gemini Batch API file for {filename} ---")
    pairs = load_aligned_data(filename)
    
    jsonl_filename = f"gemini_batch_requests_{filename.replace('.csv', '')}.jsonl"
    
    with open(jsonl_filename, 'w', encoding='utf-8') as f:
        for pair in pairs:
            prompt = get_judge_prompt(pair['raw_json'], pair['generated_text'])
            
            # Google GenAI SDK Batch JSONL format
            request_obj = {
                "custom_id": f"chunk_{pair['chunk_index']}",
                "method": "POST",
                "url": "/v1beta/models/gemini-3.1-pro:generateContent",
                "body": {
                    "contents": [{
                        "role": "user", 
                        "parts": [{"text": prompt}]
                    }],
                    "generationConfig": {
                        "responseMimeType": "application/json",
                        "temperature": 0.1
                    }
                }
            }
            f.write(json.dumps(request_obj) + "\n")
            
    print(f"\nSuccessfully generated {jsonl_filename} with {len(pairs)} requests.")
    print("Upload this file using the Google GenAI SDK Batch API for 50% cost savings at scale!")

if __name__ == "__main__":
    print("="*15)
    print(" Agri-LM Judge Agent")
    print("="*15)
    print("1. Validate locally with Ollama (Good for testing)")
    print("2. Generate Batch JSONL for Gemini 3.1 Pro (50% Cost Savings)")
    
    choice = input("\nSelect mode (1/2): ")
    target_file = "Batch 1 Range (0 - 100000).csv"
    
    if choice == '1':
        validate_with_ollama(target_file)
    elif choice == '2':
        prepare_gemini_batch(target_file)
    else:
        print("Invalid choice.")
